name: my-github-actions
on: push
jobs:
  runs-on: ubuntu-latest
  steps:

    name: Checkout-code
    -use: action/checkout@v4
    
    name: Login to GCR
    uses: docker/login-action@v2
        with:
          username: ${{ secrets.actor }}
          password: ${{ secrets.CR_PAT }}    
    name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/app:latest