name: my-github-actions
on: push
jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
        with:
          repository: Repo_test_workflows
    
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.actor }}
          password: ${{ secrets.CR_PAT }}    
    
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/app:latest