name: my-github-actions
on: push
jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}    
    
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: sofianeslimane/app:latest
  
